Repository matter-js/python-matter-server, pull requests merged in 2023-12, with the labels that each got.

#451 Lower logging of attribute changed callback
  matter_server/server/device_controller.py
Labels: maintenance

#450 Implement more aggressive retry logic for resolving and first interview
  README.md
  matter_server/server/device_controller.py
Labels: maintenance

#447 Fix open commissioning window tuple bug
  matter_server/server/device_controller.py
Labels: bugfix

#462 Log extensively during commissioning
  matter_server/server/device_controller.py
  matter_server/server/helpers/attributes.py
Labels: maintenance

#470 Allow to commission with code on network only
  matter_server/client/client.py
  matter_server/server/device_controller.py
  pyproject.toml
  tests/server/test_server.py
Labels: new-feature

#471 Optimize commission and (re)subscription flows
  matter_server/common/models.py
  matter_server/server/__main__.py
  matter_server/server/device_controller.py
Labels: maintenance

#472 Move delayed interview to own callback
  matter_server/server/device_controller.py
Labels: maintenance

#473 Bump schema version to 6
  matter_server/client/client.py
  matter_server/common/const.py
Labels: maintenance

#474 Fix some bugs in resolve node function
  matter_server/server/device_controller.py
Labels: bugfix

#481 Restore single subscription to a node instead of dual
  matter_server/server/device_controller.py
Labels: bugfix, maintenance
