Repository matter-js/python-matter-server, pull requests merged in 2023-10, with the labels that each got.

#397 Fix scripts/generate_devices.py scripts
  scripts/generate_devices.py
Labels: bugfix

#405 Bump chip wheels to 2023.11.0b1 (sdk 1.2 rc1)
  pyproject.toml
Labels: new-feature, maintenance

#414 Bump Matter SDK to 1.2.0.0
  matter_server/client/client.py
  matter_server/client/models/device_types.py
  matter_server/client/models/node.py
  matter_server/common/helpers/util.py
  matter_server/server/device_controller.py
  pyproject.toml
  scripts/generate_devices.py
Labels: dependencies

#415 Cleanup/clarify commission_on_network
  README.md
  matter_server/client/client.py
  matter_server/server/device_controller.py
Labels: maintenance

#416 Adjust subscription logic a bit
  matter_server/server/device_controller.py
Labels: maintenance

#417 Automatically re-interview a node if its software version has changed
  matter_server/server/device_controller.py
Labels: maintenance
