Repository matter-js/python-matter-server, pull requests merged in 2024-02, with the labels that each got.

#527 Shutdown Certificate Authority Manager before the stack
  matter_server/server/stack.py
Labels: bugfix

#526 Support specifying which IP addresses to listen on
  matter_server/server/__main__.py
  matter_server/server/helpers/custom_web_runner.py
  matter_server/server/server.py
  tests/server/test_server.py
Labels: new-feature

#530 Log non-text messages in websocket api
  matter_server/client/connection.py
  matter_server/server/client_handler.py
Labels: maintenance

#531 Implement zeroconf for operational node discovery
  matter_server/server/device_controller.py
  pyproject.toml
Labels: new-feature

#534 Fix small typo in attempt count
  matter_server/server/device_controller.py
Labels: maintenance

#533 Add active fabric index to diagnostics
  matter_server/client/client.py
  matter_server/client/models/node.py
Labels: maintenance

#536 Treat mdns update events as add events as safeguard
  matter_server/server/device_controller.py
Labels: maintenance

#535 Fix networkname retrieval for some wifi devices
  matter_server/client/client.py
Labels: bugfix

#537 Process the mdns messages semi parallel
  matter_server/server/device_controller.py
Labels: maintenance

#538 Refactor the interview logic a small bit
  matter_server/server/const.py
  matter_server/server/device_controller.py
Labels: maintenance

#539 Prevent duplicate interviews
  matter_server/common/helpers/util.py
  matter_server/server/device_controller.py
Labels: bugfix

#541 Ignore MDNS removal messages
  matter_server/server/device_controller.py
Labels: maintenance

#540 Use previous available state
  matter_server/server/device_controller.py
Labels: maintenance

#547 Add an initial basic dashboard
  dashboard/.gitignore
  dashboard/README.md
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/public/index.html
  dashboard/rollup.config.mjs
  dashboard/script/build
  dashboard/script/develop
  dashboard/script/setup
  dashboard/src/client/client.ts
  dashboard/src/client/connection.ts
  dashboard/src/client/exceptions.ts
  dashboard/src/client/models/model.ts
  dashboard/src/client/models/node.ts
  dashboard/src/components/dialog-box/dialog-box.ts
  dashboard/src/components/dialog-box/show-dialog-box.ts
  dashboard/src/components/ha-svg-icon.ts
  dashboard/src/entrypoint/main.ts
  dashboard/src/pages/matter-dashboard-app.ts
  dashboard/src/pages/matter-dashboard.ts
  dashboard/src/pages/matter-node-view.ts
  dashboard/src/pages/matter-server-view.ts
  dashboard/src/util/fire_event.ts
  dashboard/src/util/prevent_default.ts
  dashboard/src/util/routing.ts
  dashboard/tsconfig.json
  matter_server/client/connection.py
Labels: new-feature

#543 Adjust the linter config
  .github/workflows/test.yml
  .pre-commit-config.yaml
  dashboard/public/index.html
  dashboard/script/build
  dashboard/script/develop
  matter_server/client/models/clusters.py
  matter_server/common/helpers/json.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
  matter_server/server/server.py
  pyproject.toml
  requirements-test.txt
  scripts/generate_devices.py
  setup.cfg
  tests/common/test_parser.py
  tests/common/test_utils.py
  tests/fixtures/__init__.py
  tests/ruff.toml
  tests/server/test_server.py
Labels: ci, maintenance

#545 Fetch all Git certs and prefer them
  matter_server/server/helpers/paa_certificates.py
Labels: bugfix, maintenance

#555 Remove black and flake8 from dev dependencies (now handled by ruff)
  pyproject.toml
Labels: maintenance

#556 Filter Matter SDK logging in SDK
  matter_server/server/__main__.py
  matter_server/server/stack.py
  pyproject.toml
Labels: new-feature

#567 A few small improvements to the linter config
  pyproject.toml
Labels: ci

#568 Delay marking a node as unavailable
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#569 Enforce alphabetical sorting in ruff isort
  matter_server/common/helpers/json.py
  matter_server/server/__main__.py
  matter_server/server/device_controller.py
  matter_server/server/server.py
  matter_server/server/stack.py
  pyproject.toml
  tests/common/test_parser.py
Labels: ci, maintenance

#571 Skip push to main branch check in test workflow push
  .github/workflows/test.yml
Labels: ci

#570 Delay building of the container after publishing to PyPi
  .github/workflows/release.yml
Labels: ci

#573 Switch (back) to a single wildcard subscription per node
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#572 Some improvements to the operational node discovery using mdns
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#576 Change log level of deprecated subscribe attribute
  matter_server/server/device_controller.py
Labels: maintenance

#575 Change the default subscription ceiling to 60 seconds
  matter_server/server/device_controller.py
Labels: maintenance

#584 Remove resolve lock
  matter_server/server/device_controller.py
Labels: maintenance

#585 Fix ping node and retrieval of IP addresses
  matter_server/client/client.py
  matter_server/common/const.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#566 Fix Nullable values in write attributes procedure
  matter_server/common/helpers/util.py
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#591 Lower log level of zeroconf
  matter_server/server/__main__.py
Labels: maintenance

#590 Uniform the result of read_attribute to always return a dict
  matter_server/client/client.py
  matter_server/server/device_controller.py
Labels: maintenance

#589 A few small fixes to the share (open commissioning window) feature
  matter_server/server/device_controller.py
Labels: bugfix

#594 Catch TimeoutError while retrieving certificates
  matter_server/server/helpers/paa_certificates.py
Labels: bugfix

#593 Include (base) dashboard in the builtin-webserver
  .github/workflows/release.yml
  dashboard/src/entrypoint/main.ts
  dashboard/src/pages/matter-dashboard.ts
  matter_server/server/server.py
  pyproject.toml
  tests/server/test_server.py
Labels: new-feature

#596 Ensure that the dashboard build is included in the py wheel
  .github/workflows/release.yml
  .gitignore
  dashboard/README.md
  dashboard/script/build
  matter_server/server/server.py
  pyproject.toml
Labels: bugfix

#597 A collection of small (stability) fixes and tweaks
  matter_server/server/__main__.py
  matter_server/server/client_handler.py
  matter_server/server/device_controller.py
  matter_server/server/server.py
Labels: bugfix

#600 Do multiple ping attempts when discovering a node
  matter_server/server/device_controller.py
  matter_server/server/helpers/utils.py
Labels: maintenance

#606 Update to Matter SDK wheels 2024.2.2
  pyproject.toml
Labels: dependencies

#604 Add timeouts to sdk calls and subscription set-up
  matter_server/server/device_controller.py
Labels: maintenance

#603 Add fallback scanner for Matter nodes
  matter_server/server/device_controller.py
Labels: bugfix

#607 Add fallback log name for exceptions
  matter_server/server/device_controller.py
Labels: maintenance
