Repository matter-js/python-matter-server, pull requests merged in 2024-09, with the labels that each got.

#873 Retry subscription setup if necessary
  matter_server/server/device_controller.py
Labels: bugfix

#874 Check if setup task is actually still running
  matter_server/server/device_controller.py
Labels: bugfix

#876 Shutdown subscription after exactly 30 minutes
  matter_server/server/device_controller.py
Labels: maintenance

#880 ValvePosition attribute of EveCluster Cluster
  matter_server/common/custom_clusters.py
Labels: maintenance

#881 Cleanup: Drop setup node timer
  matter_server/server/device_controller.py
Labels: maintenance

#882 Cleanup: Remove fallback node scanner
  matter_server/server/device_controller.py
Labels: maintenance

#884 Support local update file for OTA
  matter_server/server/device_controller.py
  matter_server/server/ota/provider.py
Labels: new-feature

#885 Select OTA Provider port randomly
  matter_server/server/ota/provider.py
Labels: bugfix

#886 Use to_thread where appropriate
  matter_server/server/ota/provider.py
Labels: maintenance

#887 MotionSensitivity attribute within the Eve Cluster
  matter_server/common/custom_clusters.py
Labels: new-feature

#890 Update to Matter SDK wheels 2024.9.0
  matter_server/server/sdk.py
  pyproject.toml
Labels: maintenance

#892 Use interval floor of 0 for ICD devices
  matter_server/server/device_controller.py
Labels: maintenance

#893 Prevent Eve devices with newer firmware to be polled
  matter_server/common/custom_clusters.py
Labels: maintenance
