Repository matter-js/python-matter-server, pull requests merged in 2024-04, with the labels that each got.

#661 Drop Python safety module from dependencies
  pyproject.toml
Labels: dependencies

#669 Expand dashboard to explore Node values
  dashboard/src/client/client.ts
  dashboard/src/client/models/descriptions.ts
  dashboard/src/client/models/model.ts
  dashboard/src/client/models/node.ts
  dashboard/src/entrypoint/main.ts
  dashboard/src/pages/components/footer.ts
  dashboard/src/pages/components/header.ts
  dashboard/src/pages/components/node-details.ts
  dashboard/src/pages/components/server-details.ts
  dashboard/src/pages/matter-cluster-view.ts
  dashboard/src/pages/matter-dashboard-app.ts
  dashboard/src/pages/matter-dashboard.ts
  dashboard/src/pages/matter-endpoint-view.ts
  dashboard/src/pages/matter-node-view.ts
  dashboard/src/pages/matter-server-view.ts
  dashboard/src/util/routing.ts
  pyproject.toml
  scripts/generate_descriptions.py
Labels: new-feature

#662 Add verbose log level
  matter_server/common/const.py
  matter_server/server/__main__.py
  matter_server/server/client_handler.py
  matter_server/server/device_controller.py
Labels: maintenance

#676 Some small tweaks to the subscripions logic
  matter_server/client/client.py
  matter_server/server/device_controller.py
Labels: maintenance
