Repository matter-js/python-matter-server, pull requests merged in 2024-07, with the labels that each got.

#781 Update dashboard definition files
  dashboard/script/setup
  dashboard/src/client/models/descriptions.ts
Labels: maintenance

#782 Update to Matter SDK wheels 2024.6.4
  matter_server/server/sdk.py
  pyproject.toml
Labels: maintenance

#786 Add flag for test-net DCL
  matter_server/server/__main__.py
  matter_server/server/helpers/paa_certificates.py
  matter_server/server/server.py
Labels: new-feature

#788 Convert --enable-test-net-dcl to a flag argument
  matter_server/server/__main__.py
Labels: maintenance

#789 Add custom cluster definition for ThirdReality Energy reporting
  matter_server/common/custom_clusters.py
Labels: maintenance

#777 Enable dashboard in dev build
  Dockerfile.dev
Labels: maintenance

#799 Add direct bluetooth commissioning support
  matter_server/common/models.py
  matter_server/server/__main__.py
  matter_server/server/device_controller.py
  matter_server/server/server.py
  matter_server/server/stack.py
Labels: new-feature

#709 Add software update capability
  Dockerfile
  matter_server/client/client.py
  matter_server/common/const.py
  matter_server/common/errors.py
  matter_server/common/models.py
  matter_server/server/__main__.py
  matter_server/server/const.py
  matter_server/server/device_controller.py
  matter_server/server/helpers/__init__.py
  matter_server/server/helpers/paa_certificates.py
  matter_server/server/ota/__init__.py
  matter_server/server/ota/dcl.py
  matter_server/server/ota/provider.py
  matter_server/server/server.py
  tests/server/ota/test_dcl.py
Labels: new-feature

#805 Matter update fixes
  matter_server/common/models.py
  matter_server/server/ota/provider.py
Labels: bugfix

#804 Add support for commissioning nodes to debug UI
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/client/client-context.ts
  dashboard/src/client/models/descriptions.ts
  dashboard/src/components/dialog-box/dialog-box.ts
  dashboard/src/components/dialog-box/show-dialog-box.ts
  dashboard/src/components/dialogs/commission-node-dialog/commission-node-dialog.ts
  dashboard/src/components/dialogs/commission-node-dialog/commission-node-existing.ts
  dashboard/src/components/dialogs/commission-node-dialog/commission-node-thread.ts
  dashboard/src/components/dialogs/commission-node-dialog/commission-node-wifi.ts
  dashboard/src/components/dialogs/commission-node-dialog/show-commission-node-dialog.ts
  dashboard/src/pages/components/node-details.ts
  dashboard/src/pages/components/server-details.ts
  dashboard/src/pages/matter-cluster-view.ts
  dashboard/src/pages/matter-dashboard-app.ts
  dashboard/src/util/clone_class.ts
Labels: new-feature

#806 Add update button to debug UI
  dashboard/src/client/models/model.ts
  dashboard/src/client/models/node.ts
  dashboard/src/pages/components/node-details.ts
Labels: maintenance

#809 Update to Matter SDK wheels 2024.7.1
  pyproject.toml
Labels: maintenance

#814 Debug UI: Fix update progres and add share button
  dashboard/src/pages/components/node-details.ts
Labels: maintenance

#819 Trim OTA checksum for whitespace before comparing
  matter_server/server/ota/provider.py
Labels: bugfix

#818 Add setup script for development and adjust readme
  README.md
  scripts/setup.sh
Labels: maintenance

#827 Log when the Matter server finished startup
  matter_server/server/server.py
Labels: maintenance

#828 Fix writing optional Nullable values
  matter_server/common/helpers/util.py
  tests/common/test_parser.py
Labels: bugfix

#829 Don't regard update information without a valid URL
  matter_server/server/device_controller.py
  matter_server/server/ota/dcl.py
  tests/server/ota/fixtures/4442-67-197888.json
  tests/server/ota/fixtures/4442-67-197910.json
  tests/server/ota/fixtures/4442-67-198340.json
  tests/server/ota/fixtures/4442-67.json
  tests/server/ota/test_dcl.py
Labels: bugfix

#834 Fix OTA URL check syntax
  matter_server/server/device_controller.py
Labels: bugfix
