Repository matter-js/python-matter-server, pull requests merged in 2024-05, with the labels that each got.

#684 Handle value specified as bytes received as integer
  matter_server/common/helpers/util.py
  tests/common/test_parser.py
Labels: bugfix

#675 Bump chip wheels to 2024.4.1 (Matter SDK 1.3)
  matter_server/client/models/device_types.py
  matter_server/server/device_controller.py
  pyproject.toml
  scripts/generate_devices.py
Labels: dependencies

#688 Deduplicate PAA certificates using Subject Key Identifier
  matter_server/server/helpers/paa_certificates.py
Labels: new-feature

#692 Use ping binary for IPv6
  matter_server/server/helpers/utils.py
Labels: maintenance

#694 Fix imports at runtime
  matter_server/common/models.py
  matter_server/server/stack.py
Labels: bugfix

#706 Use mkdirs for paa_root_certs as the intermediate directories do not exist
  matter_server/server/helpers/paa_certificates.py
Labels: bugfix

#708 Pass PAA certificate path by default to data directory
  Dockerfile
Labels: bugfix

#715 Refactor logic for handling Custom Clusters/Attributes
  matter_server/client/client.py
  matter_server/common/const.py
  matter_server/common/custom_clusters.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
  scripts/generate_descriptions.py
Labels: new-feature, breaking-change, maintenance

#716 Use SetRawAttributeUpdateCallback to support custom clusters
  matter_server/server/__main__.py
  matter_server/server/device_controller.py
  pyproject.toml
Labels: new-feature, maintenance

#717 Refactor and rename _resolve_node to _establish_case_session
  matter_server/common/errors.py
  matter_server/server/device_controller.py
Labels: maintenance

#720 Refactor MatterDeviceController
  matter_server/server/device_controller.py
  matter_server/server/sdk.py
  matter_server/server/server.py
  tests/server/test_server.py
Labels: maintenance

#722 Fix custom attribute polling due to redundant lock
  matter_server/server/device_controller.py
Labels: bugfix

#724 Only Poll individual attributes in custom Eve cluster
  matter_server/common/custom_clusters.py
  matter_server/server/device_controller.py
Labels: bugfix

#725 Fix arguments in ChipDeviceControllerWrapper
  matter_server/server/sdk.py
Labels: bugfix

#726 Update the descriptions.ts to account for latest changes
  dashboard/src/client/models/descriptions.ts
  scripts/generate_descriptions.py
Labels: maintenance

#727 Fix open commissioning window
  matter_server/server/sdk.py
Labels: bugfix

#728 Fix SDK reentrancy issues
  matter_server/server/sdk.py
  pyproject.toml
Labels: bugfix

#731 Remove node from polled attributes when its removed
  matter_server/server/device_controller.py
Labels: bugfix
