Repository matter-js/python-matter-server, pull requests merged in 2024-01, with the labels that each got.

#486 Remove (pointless) resolve lock
  matter_server/server/device_controller.py
Labels: bugfix

#490 Fix json serialization for discovery api
  matter_server/server/device_controller.py
Labels: bugfix

#489 Add pagination for vendors query
  matter_server/server/vendor_info.py
Labels: bugfix

#498 Cancel pending interviews when removing a node
  matter_server/server/device_controller.py
Labels: maintenance

#501 Scope link-local IPv6 addresses received from WebSocket
  matter_server/server/__main__.py
  matter_server/server/device_controller.py
  matter_server/server/server.py
  pyproject.toml
  tests/server/test_server.py
Labels: bugfix

#497 Update typo in the readme
  README.md
Labels: maintenance

#500 Print result of device removal
  matter_server/server/device_controller.py
Labels: new-feature

#503 Fix Node removal
  matter_server/server/device_controller.py
Labels: bugfix

#508 Add diagnostics for matter nodes
  matter_server/client/client.py
  matter_server/client/models/node.py
  matter_server/common/helpers/util.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
  matter_server/server/helpers/utils.py
  matter_server/server/vendor_info.py
  tests/common/test_utils.py
Labels: new-feature

#514 Improvements and bugfixes for persistent storage of node data
  matter_server/server/device_controller.py
  scripts/example.py
Labels: bugfix, maintenance

#515 Guard node resolving with a lock
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#517 Add interview node command to client
  matter_server/client/client.py
Labels: maintenance

#516 Fix model for CommissioningParameters in client
  matter_server/client/client.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
Labels: bugfix

#520 Use our own global models for CommissionableNodeData and Commissionin…
  matter_server/client/client.py
  matter_server/common/const.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
Labels: new-feature, maintenance

#518 Speedup diagnostics
  matter_server/client/client.py
  matter_server/client/models/node.py
  matter_server/server/device_controller.py
  matter_server/server/helpers/utils.py
Labels: bugfix, maintenance
