Repository matter-js/python-matter-server, pull requests merged in 2024-12, with the labels that each got.

#993 Bump to Matter 1.4 wheels and device types
  dashboard/src/client/models/descriptions.ts
  matter_server/client/models/device_types.py
  matter_server/client/models/node.py
  pyproject.toml
Labels: new-feature, breaking-change

#981 Move Websocket commands doc into docs directory
  README.md
  docs/websockets_api.md
Labels: ci, docs

#999 Explain how to start the server with debug log-level
  README.md
Labels: maintenance, docs

#1008 Restructure the documentation in more smaller parts
  DEVELOPMENT.md
  README.md
  compose.yml
  docs/docker.md
  docs/matter_logo.svg
  docs/os_requirements.md
  docs/websockets_api.md
Labels: maintenance, docs

#1014 Use atomic writes for the storage file
  matter_server/server/storage.py
  pyproject.toml
Labels: bugfix

#1023 Fix settings file storage at first/clean startup
  matter_server/server/storage.py
Labels: bugfix
