Repository matter-js/python-matter-server, pull requests merged in 2024-03, with the labels that each got.

#612 Drop Python 3.10 support
  .github/workflows/release.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: new-feature, maintenance

#610 Refactor locking and timeout to sdk access
  matter_server/server/device_controller.py
Labels: bugfix, maintenance

#618 Several improvements to resolving and (re)subscribing to nodes
  matter_server/server/device_controller.py
  matter_server/server/helpers/utils.py
  matter_server/server/server.py
Labels: bugfix, maintenance

#620 Better logging of client errors
  matter_server/server/client_handler.py
Labels: maintenance

#619 Tweak subscription ceiling based on routing role
  matter_server/server/device_controller.py
Labels: maintenance

#621 Remove executor limit
  matter_server/server/device_controller.py
Labels: maintenance

#622 Add server argument to specify custom PAA root certificate location
  matter_server/server/__main__.py
  matter_server/server/const.py
  matter_server/server/device_controller.py
  matter_server/server/helpers/paa_certificates.py
  matter_server/server/server.py
Labels: new-feature

#623 Add warning if node setup takes too long
  matter_server/server/device_controller.py
Labels: maintenance

#652 Add remove node support to the dashboard
  dashboard/src/pages/matter-node-view.ts
Labels: maintenance

#656 Allow the dashboard to be hosted in ingress
  dashboard/src/entrypoint/main.ts
Labels: bugfix

#655 Use async resolve node
  matter_server/server/device_controller.py
Labels: maintenance

#658 Skip unneeded dataclass conversion in storage
  matter_server/server/device_controller.py
Labels: maintenance
