Repository matter-js/python-matter-server, pull requests merged in 2024-06, with the labels that each got.

#736 Use secrets to generate the discriminator
  matter_server/server/device_controller.py
Labels: maintenance

#737 Introduce loop property to get the event loop
  matter_server/server/device_controller.py
  matter_server/server/server.py
Labels: maintenance

#735 Fix and improve node unavailable handling
  matter_server/server/device_controller.py
Labels: bugfix

#747 Remove unnecessary debug print statements
  matter_server/server/server.py
Labels: maintenance

#748 Move MatterDeviceController instantiation to start()
  matter_server/server/server.py
Labels: bugfix

#749 Fix link-local address pinging
  matter_server/server/device_controller.py
Labels: bugfix

#751 Reintroduce ability to get IP addresses without scope
  matter_server/client/client.py
  matter_server/common/models.py
  matter_server/server/device_controller.py
Labels: maintenance

#738 Update to Matter SDK wheels 2024.6.0
  matter_server/server/device_controller.py
  matter_server/server/sdk.py
  matter_server/server/stack.py
  pyproject.toml
Labels: new-feature

#752 Improve the open commissioning window command
  matter_server/server/device_controller.py
Labels: maintenance

#760 Update to Matter SDK wheels 2024.6.1
  pyproject.toml
Labels: maintenance

#763 Edge case defect when importing the first test node into dashboard
  matter_server/server/device_controller.py
Labels: bugfix

#765 Convert to asyncio Matter SDK API
  matter_server/server/device_controller.py
  matter_server/server/sdk.py
  pyproject.toml
Labels: maintenance

#768 Fix writing of Nullable attributes
  matter_server/common/helpers/util.py
  matter_server/server/device_controller.py
  tests/common/test_parser.py
Labels: bugfix

#762 Added custom cluster for energy consumption data for Neo smart plug
  matter_server/common/custom_clusters.py
Labels: maintenance

#770 Don't use threadsafe variant in signal_event
  matter_server/server/server.py
Labels: maintenance

#771 Override Liveness timeout on shutdown
  matter_server/server/device_controller.py
  matter_server/server/sdk.py
Labels: maintenance

#772 Raise InvalidServerVersion when Server is too old too
  matter_server/client/client.py
  matter_server/client/connection.py
  matter_server/client/exceptions.py
  matter_server/server/server.py
Labels: maintenance

#723 Use GetConnectedDevice directly to get device proxy
  matter_server/server/sdk.py
Labels: maintenance
