Repository matter-js/python-matter-server, pull requests merged in 2025-09, with the labels that each got.

#1232 fix matter binding detele error
  dashboard/src/components/dialogs/acl/model.ts
  dashboard/src/components/dialogs/binding/model.ts
  dashboard/src/components/dialogs/binding/node-binding-dialog.ts
Labels: bugfix

#1243 replace async-timeout with asyncio.timeout
  matter_server/server/client_handler.py
  matter_server/server/helpers/utils.py
  pyproject.toml
Labels: maintenance

#1248 Bump OTA Provider to 2025.9.0
  Dockerfile
Labels: dependencies

#1250 Announce Matter Server rewrite and maintenance mode
  README.md
Labels: docs
