Repository matter-js/python-matter-server, pull requests merged in 2025-05, with the labels that each got.

#1143 Bump OTA Provider to 2025.5.0
  Dockerfile
Labels: dependencies

#1137 Add Mounted device types (1.4)
  dashboard/src/client/models/descriptions.ts
  matter_server/client/models/device_types.py
Labels: new-feature

#1144 Improve Matter DNS-SD service parsing
  .pre-commit-config.yaml
  matter_server/server/device_controller.py
  matter_server/server/server.py
  tests/test_device_controller.py
Labels: bugfix, maintenance
